/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;


import static Views.Sistema.txt_dniPaciente_Pago;
import static Views.Sistema.txt_idcita_pago;
import static Views.Sistema.txt_nombrepaciente_pago;
import conexionSQLServer.logicaCita;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;


/**
 *
 * @author ERIK RUBIO
 */
public class ListarCitas extends javax.swing.JFrame {

 
    /**
     * Creates new form ListarCitas
     */
    public ListarCitas() {
        initComponents();
        
      FechasJdate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        combo_fechainicio_listarcita = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        combo_fechafin_listarcita = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        txt_Buscarpaciente_listarcita = new javax.swing.JTextField();
        btn_sincronizar_listacita = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_listarcita = new javax.swing.JTable();
        btn_buscar_listarcita = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(51, 138, 182))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(70, 106, 124));
        jLabel9.setText("Fecha inicio");

        combo_fechainicio_listarcita.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(70, 106, 124));
        jLabel14.setText("Fecha Fin");

        combo_fechafin_listarcita.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(70, 106, 124));
        jLabel17.setText("Buscar paciente");

        txt_Buscarpaciente_listarcita.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_Buscarpaciente_listarcita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Buscarpaciente_listarcitaActionPerformed(evt);
            }
        });

        btn_sincronizar_listacita.setBackground(new java.awt.Color(51, 51, 51));
        btn_sincronizar_listacita.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        btn_sincronizar_listacita.setForeground(new java.awt.Color(255, 255, 255));
        btn_sincronizar_listacita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/actualizar.png"))); // NOI18N
        btn_sincronizar_listacita.setText("Sincronizar");
        btn_sincronizar_listacita.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_sincronizar_listacita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sincronizar_listacitaActionPerformed(evt);
            }
        });
        btn_sincronizar_listacita.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_sincronizar_listacitaKeyReleased(evt);
            }
        });

        tabla_listarcita = new javax.swing.JTable(){
            public boolean isCellEditable (int row, int col){
                for (int i=0;i<tabla_listarcita.getRowCount();i++){
                    if (row ==i){
                        return false;
                    }
                }
                return true;
            }
        };
        tabla_listarcita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_listarcita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_listarcitaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_listarcita);

        btn_buscar_listarcita.setBackground(new java.awt.Color(51, 51, 51));
        btn_buscar_listarcita.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        btn_buscar_listarcita.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar_listarcita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/buscar.png"))); // NOI18N
        btn_buscar_listarcita.setText("Buscar");
        btn_buscar_listarcita.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_buscar_listarcita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_listarcitaActionPerformed(evt);
            }
        });
        btn_buscar_listarcita.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_buscar_listarcitaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_fechainicio_listarcita, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(combo_fechafin_listarcita, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(btn_sincronizar_listacita))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Buscarpaciente_listarcita, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscar_listarcita))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(combo_fechainicio_listarcita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_fechafin_listarcita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_sincronizar_listacita))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Buscarpaciente_listarcita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(btn_buscar_listarcita, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Citas", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 993, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Buscarpaciente_listarcitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Buscarpaciente_listarcitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Buscarpaciente_listarcitaActionPerformed
 public void FechasJdate() {
        Calendar micalendario = new GregorianCalendar();
       

        combo_fechainicio_listarcita.setCalendar(micalendario);
        combo_fechafin_listarcita.setCalendar(micalendario);
    }
     
 
    logicaCita citaprincipal = new logicaCita();
    private void btn_sincronizar_listacitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sincronizar_listacitaActionPerformed
        
        SimpleDateFormat simpleDF1 = new SimpleDateFormat("yyyy-MM-dd");
        String fechainicio = simpleDF1.format(combo_fechainicio_listarcita.getDate());
        SimpleDateFormat simpleDF2 = new SimpleDateFormat("yyyy-MM-dd");
        String fechafin = simpleDF2.format(combo_fechafin_listarcita.getDate());
     
    
        citaprincipal.mostrarListaCitas(fechainicio,fechafin,tabla_listarcita);

        
    }//GEN-LAST:event_btn_sincronizar_listacitaActionPerformed

    private void btn_sincronizar_listacitaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_sincronizar_listacitaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sincronizar_listacitaKeyReleased
    logicaCita citalistar = new logicaCita();

    private void btn_buscar_listarcitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_listarcitaActionPerformed
        if (txt_Buscarpaciente_listarcita.getText().isEmpty()) {
            //mostrarTablaListadoPaciente();
            //limpiar();
        } else {
            citalistar.Buscarcita(txt_Buscarpaciente_listarcita.getText(),combo_fechainicio_listarcita.getDate().toString(),combo_fechafin_listarcita.getDate().toString(), tabla_listarcita);
            //limpiarTextdelBuscador();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscar_listarcitaActionPerformed

    private void btn_buscar_listarcitaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_buscar_listarcitaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscar_listarcitaKeyReleased

    private void tabla_listarcitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_listarcitaMouseClicked
    if (evt.getClickCount()==2){ //EVENTO DOBLE CLICK PARA SELECCIONAR LOS ELEMENTOS DE UNA TABLA
        // CAPTURAR LOS DATOS DE LA TABLA Y ENVIAR A LAS CAJAS DE TEXTO
        int fila = tabla_listarcita.getSelectedRow();
        if (fila >= 0) {

            int Seleccionar = tabla_listarcita.rowAtPoint(evt.getPoint());
            txt_idcita_pago.setText(String.valueOf(tabla_listarcita.getValueAt(Seleccionar, 0)));
            txt_dniPaciente_Pago.setText(String.valueOf(tabla_listarcita.getValueAt(Seleccionar, 3)));
            txt_nombrepaciente_pago.setText(String.valueOf(tabla_listarcita.getValueAt(Seleccionar, 4)));        
            dispose(); //CERRAR FORMULARIO
        } else {
            JOptionPane.showMessageDialog(null, "NO SELECCIONO FILA");
        }
        
        }
        
        
    }//GEN-LAST:event_tabla_listarcitaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarCitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar_listarcita;
    private javax.swing.JButton btn_sincronizar_listacita;
    private com.toedter.calendar.JDateChooser combo_fechafin_listarcita;
    private com.toedter.calendar.JDateChooser combo_fechainicio_listarcita;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable tabla_listarcita;
    private javax.swing.JTextField txt_Buscarpaciente_listarcita;
    // End of variables declaration//GEN-END:variables
   

   
}
