/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import conexionSQLServer.logicaTipoconsulta;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static Views.Sistema.txt_codigo_Producto_pago;
import static Views.Sistema.txt_descripcion_producto_pago;
import static Views.Sistema.txt_costo_producto_pago;
import static Views.Sistema.txt_cantidad_producto_pago;
import static Views.Sistema.txt_monto_pago;

/**
 *
 * @author ERIK RUBIO
 */
public class ListarServicios extends javax.swing.JFrame {

    /**
     * Creates new form ListarServicios
     */
    public ListarServicios() {
        initComponents();
        mostrarTablaListadoProductosServicios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_productos_servicios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(70, 106, 124));
        jLabel17.setText("PRODUCTO O SERVICIOS ");

        tabla_productos_servicios = new javax.swing.JTable(){
            public boolean isCellEditable (int row, int col){
                for (int i=0;i<tabla_productos_servicios.getRowCount();i++){
                    if (row ==i){
                        return false;
                    }
                }
                return true;
            }
        };
        tabla_productos_servicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tabla_productos_servicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_productos_serviciosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_productos_servicios);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(jLabel17)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("LISTA DE PRODUCTOS O SERVICIOS", jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarTablaListadoProductosServicios() {

        try {
            DefaultTableModel modelo;
            logicaTipoconsulta func = new logicaTipoconsulta();
            modelo = func.mostrarproductosservicios();
            tabla_productos_servicios.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }

    }

    private void tabla_productos_serviciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_productos_serviciosMouseClicked
        if (evt.getClickCount() == 2) { //EVENTO DOBLE CLICK PARA SELECCIONAR LOS ELEMENTOS DE UNA TABLA
            // CAPTURAR LOS DATOS DE LA TABLA Y ENVIAR A LAS CAJAS DE TEXTO
            int fila = tabla_productos_servicios.getSelectedRow();
            if (fila >= 0) {

                int Seleccionar = tabla_productos_servicios.rowAtPoint(evt.getPoint());
                txt_codigo_Producto_pago.setText(String.valueOf(tabla_productos_servicios.getValueAt(Seleccionar, 0)));
                txt_descripcion_producto_pago.setText(String.valueOf(tabla_productos_servicios.getValueAt(Seleccionar, 1)));
                txt_costo_producto_pago.setText(String.valueOf(tabla_productos_servicios.getValueAt(Seleccionar, 2)));

                dispose(); //CERRAR FORMULARIO

                String cantidad = "1";
                txt_cantidad_producto_pago.setText(cantidad);
                double cantidadproducto = Double.parseDouble(txt_cantidad_producto_pago.getText());
                double costoproducto = Double.parseDouble(txt_costo_producto_pago.getText());
                double Resultado = cantidadproducto * costoproducto;
                System.out.println(cantidadproducto + " " + costoproducto + " " + Resultado);
                String valor = String.valueOf(Resultado);
                
                txt_monto_pago.setText(valor);
                
               // String 

            } else {
                JOptionPane.showMessageDialog(null, "NO SELECCIONO FILA");
            }

        }

    }//GEN-LAST:event_tabla_productos_serviciosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarServicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTable tabla_productos_servicios;
    // End of variables declaration//GEN-END:variables
}
